import 'package:flutter/material.dart';

/// Paketleme kategorileri
enum PackingCategory { documents, clothes, tech, toiletries, accessories, other }

/// Paketleme öğesi
class PackingItem {
  final String id;
  final String name;
  final PackingCategory category;
  final bool isPacked;
  final bool isAutoGenerated;

  const PackingItem({
    required this.id,
    required this.name,
    required this.category,
    this.isPacked = false,
    this.isAutoGenerated = false,
  });

  PackingItem copyWith({bool? isPacked}) => PackingItem(
    id: id, name: name, category: category, 
    isPacked: isPacked ?? this.isPacked, isAutoGenerated: isAutoGenerated,
  );

  String get categoryLabel => switch (category) {
    PackingCategory.documents => 'Belgeler',
    PackingCategory.clothes => 'Kıyafetler',
    PackingCategory.tech => 'Teknoloji',
    PackingCategory.toiletries => 'Kişisel Bakım',
    PackingCategory.accessories => 'Aksesuarlar',
    PackingCategory.other => 'Diğer',
  };

  IconData get categoryIcon => switch (category) {
    PackingCategory.documents => Icons.folder_rounded,
    PackingCategory.clothes => Icons.checkroom_rounded,
    PackingCategory.tech => Icons.devices_rounded,
    PackingCategory.toiletries => Icons.sanitizer_rounded,
    PackingCategory.accessories => Icons.watch_rounded,
    PackingCategory.other => Icons.inventory_2_rounded,
  };

  Color get categoryColor => switch (category) {
    PackingCategory.documents => const Color(0xFFE74C3C),
    PackingCategory.clothes => const Color(0xFF3498DB),
    PackingCategory.tech => const Color(0xFF9B59B6),
    PackingCategory.toiletries => const Color(0xFF1ABC9C),
    PackingCategory.accessories => const Color(0xFFF39C12),
    PackingCategory.other => const Color(0xFF95A5A6),
  };
}

/// Seyahat modeli
class Trip {
  final String id;
  final String destination;
  final DateTime startDate;
  final DateTime endDate;
  final String? coverImageUrl;
  final String? notes;
  final Color accentColor;
  final List<PackingItem> packingList;

  const Trip({
    required this.id,
    required this.destination,
    required this.startDate,
    required this.endDate,
    this.coverImageUrl,
    this.notes,
    required this.accentColor,
    this.packingList = const [],
  });

  bool get isUpcoming => startDate.isAfter(DateTime.now());
  bool get isPast => endDate.isBefore(DateTime.now());
  bool get isOngoing => !isUpcoming && !isPast;

  int get daysUntil => startDate.difference(DateTime.now()).inDays;
  int get duration => endDate.difference(startDate).inDays;

  int get packedCount => packingList.where((i) => i.isPacked).length;
  double get packProgress => packingList.isEmpty ? 0 : packedCount / packingList.length;

  /// Destinasyona göre emoji
  String get emoji {
    final d = destination.toLowerCase();
    if (d.contains('italy') || d.contains('roma') || d.contains('italya')) return '🇮🇹';
    if (d.contains('cappadocia') || d.contains('kapadokya')) return '🎈';
    if (d.contains('paris') || d.contains('france')) return '🇫🇷';
    if (d.contains('japan') || d.contains('tokyo')) return '🇯🇵';
    if (d.contains('beach') || d.contains('summer')) return '🏖️';
    if (d.contains('winter') || d.contains('ski')) return '⛷️';
    return '✈️';
  }

  Trip copyWith({List<PackingItem>? packingList, String? notes}) => Trip(
    id: id, destination: destination, startDate: startDate, endDate: endDate,
    coverImageUrl: coverImageUrl, notes: notes ?? this.notes, accentColor: accentColor,
    packingList: packingList ?? this.packingList,
  );
}
